# Generated by Django 5.0 on 2024-07-11 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='created_At',
            new_name='created_at',
        ),
    ]
